/*
 * This source file was generated by the Gradle 'init' task
 */
package org.aimt;
import org.chocosolver.solver.*;
import org.chocosolver.solver.variables.IntVar;
import org.chocosolver.util.tools.ArrayUtils;

import java.util.stream.IntStream;

public class ReferenceTable {
    int rows,cols,domain;

    Model csp;
    IntVar[][] ptr_matrix;
    IntVar[][] occ_matrix;

    public ReferenceTable(Model m, int n, int nn, int d){
        this.csp = m;
        this.ptr_matrix = m.intVarMatrix(n, nn, 0,d);
        this.occ_matrix = m.intVarMatrix(n, d+1, 0, nn);

        int[] values = IntStream.range(0, d+1).toArray();
        for(int i=0;i<n;i++) 
            m.globalCardinality(ptr_matrix[i], values, occ_matrix[i], true);
    }
}
